name: Compile LaTeX and Save CV

on:
  push:
    branches:
      - main
  schedule:
      - cron: '0 * * * *'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3

    - name: Checkout private LaTeX repo
      uses: actions/checkout@v3
      with:
        repository: sahiljhawar/cv_private
        token: ${{ secrets.LATEX_BUILD }}
        path: latex_source

    - name: ls it
      run: ls latex_source

    - name: Cache TeX Live
      id: cache-texlive
      uses: actions/cache@v3
      with:
        path: /usr/local/texlive
        key: texlive-${{ runner.os }}-2024
        restore-keys: |
          texlive-${{ runner.os }}-

    - name: Set up LaTeX environment
      if: steps.cache-texlive.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Compile LaTeX document
      run: |
        cd SahilJhawar_CV
        pdflatex main.tex

    - name: Move compiled CV to main repo
      run: |
        mv latex_source/cv.pdf ./SahilJhawar_CV.pdf

    - name: Commit and push CV
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit --allow-empty -m 'Update CV'
        git push
      env:
        GH_TOKEN: ${{ secrets.LATEX_BUILD }}
