name: Compile LaTeX and Save CV

on:
  push:
    branches:
      - main
    paths: 
      - '.github/workflows/cv.yml'
  schedule:
      - cron: '0 1 * * *'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3

    - name: Checkout private LaTeX repo
      uses: actions/checkout@v3
      with:
        repository: sahiljhawar/cv_private
        token: ${{ secrets.LATEX_BUILD }}
        path: latex_source
        
    - uses: xu-cheng/latex-action@v3
      with:
        root_file: latex_source/SahilJhawar_CV/main.tex
        work_in_root_file_dir: true
        args: "-pdf -interaction=nonstopmode -bibtex -f"
      continue-on-error: true
    
    - name: ls
      run: ls /home/runner/work/sahiljhawar/sahiljhawar/latex_source/SahilJhawar_CV
        
    - name: Move compiled CV to main repo
      run: |
        mv /home/runner/work/sahiljhawar/sahiljhawar/latex_source/SahilJhawar_CV/main.pdf ./SahilJhawar_CV.pdf

    - name: Committing changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          add_options: "-A"
          commit_message: Update CV
          commit_options: "--allow-empty"
