name: Compile LaTeX and Save CV

on:
  push:
    branches:
      - main
  schedule:
      - cron: '0 * * * *'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3

    - name: Checkout private LaTeX repo
      uses: actions/checkout@v3
      with:
        repository: sahiljhawar/cv_private
        token: ${{ secrets.LATEX_BUILD }}
        path: latex_source
        
    - uses: xu-cheng/latex-action@v3
      with:
        root_file: latex_source/SahilJhawar_CV/main.tex
        continue_on_error: true
        
    - name: Move compiled CV to main repo
      run: |
        mv cv.pdf ./SahilJhawar_CV.pdf

    - name: Commit and push CV
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add SahilJhawar_CV.pdf
        git commit --allow-empty -m 'Update CV'
        git push
      env:
        GH_TOKEN: ${{ secrets.LATEX_BUILD }}
